# nydus-snapshotter Helm Chart Values

# -- nydus-snapshotter name
name: nydus-snapshotter
# -- Image repository
image: ghcr.io/containerd/nydus-snapshotter
# -- Image tag
tag: v0.6.1
# -- Image pull policy
pullPolicy: Always
# -- Let nydus-snapshotter run in host network
hostNetwork: true
# -- Host Aliases
hostAliases: []
# -- Args to overwrite default nydus-snapshotter startup command
args: []
# -- Pod resource requests and limits
resources:
  requests:
    cpu: "0"
    memory: "0"
  limits:
    cpu: "2"
    memory: "2Gi"
# -- Pod priorityClassName
priorityClassName: ""
# -- Node labels for pod assignment
nodeSelector: {"ai.tensorchord.node-type":"cache"}
# -- Pod terminationGracePeriodSeconds
terminationGracePeriodSeconds:
# -- List of node taints to tolerate
tolerations: []
# -- Pod annotations
podAnnotations: {}
# -- Pod labels
podLabels: {}
# -- Daemonset annotations
daemonsetAnnotations: {}

dragonfly:
  # -- Enable dragonfly
  enable: true
  mirrorConfig:
  - host: "http://127.0.0.1:65001"
    auth_through: false
    headers:
      "X-Dragonfly-Registry": "https://index.docker.io"
    ping_url: "http://127.0.0.1:40901/server/ping"
